name: deploy_frontend

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: ebujfrontend
  
jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push fe
        id: docker_build_fe
        uses: docker/build-push-action@v2
        with:
          context: react/
          push: true
          tags: devnevaan/eb-uj:frontend-${{ github.sha }} 
  
#   azure-deployment:
#     runs-on: ubuntu-latest
#     needs: build-container
#     steps:
#       - 
#         name: 'Run Azure webapp deploy action using publish profile credentials'
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }} 
#           images: devnevaan/eb-uj:backend-${{ github.sha }} 
#           publish-profile: ${{ secrets.azureWebAppPublishProfile }}
